add: bopl-battle (BepInEx)
ebkr/r2modmanPlus pull request #1300
Opened 2024-04-18 13:47 UTC by ethangreen-dev

2024-04-18 14:04 UTC, anttimaki requested changes
Copy-pasted API endpoint, otherwise LGTM.

2024-04-18 14:04 UTC, anttimaki commented on src/model/game/GameManager.ts
> +            "https://thunderstore.io/c/palworld/api/v1/package/", EXCLUSIONS,
The URL should be updated.

2024-04-18 14:15 UTC, ethangreen-dev commented on src/model/game/GameManager.ts
> +            "https://thunderstore.io/c/palworld/api/v1/package/", EXCLUSIONS,
Thanks for catching that, fixed.

2024-04-18 14:33 UTC, anttimaki approved these changes

2024-04-18 18:21 UTC, mathlover3 commented
how long will it be untill its added?

2024-04-18 20:05 UTC, AbstractMelon commented
> how long will it be untill its added?

Patience david

2024-04-22 06:28 UTC, anttimaki commented
Closing in favor of #1301 which includes these changes too.

2024-04-22 06:28 UTC, closed without merging