More immutable profile
ebkr/r2modmanPlus pull request #1579
Opened 2024-12-05 11:49 UTC by VilppeRiskidev

2024-12-05 13:18 UTC, VilppeRiskidev commented
This kind of is two things in one, would've been better to split into two (or even more...) separate PRs. Upcoming PRs will be kept smaller.

2024-12-09 09:14 UTC, anttimaki requested changes
Requires a small bug fix, otherwise looks good!

2024-12-09 09:14 UTC, anttimaki commented on src/r2mm/installing/ConflictManagementProviderImpl.ts
> +    async resolveConflicts(mods: ManifestV2[], profile: ImmutableProfile): Promise<R2Error | void> {
Minor: clean up `Profile` from imports.

2024-12-13 07:17 UTC, anttimaki approved these changes
Nice

2024-12-13 07:18 UTC, merged