Clean up the download state management Vuex store and it's usages
ebkr/r2modmanPlus pull request #1596
Opened 2024-12-18 15:43 UTC by VilppeRiskidev

- Remove assignId field
- Remove downloadObject field
- Rename some fields and functions to be more descriptive
- assignId is no longer passed unnecessarily when calling vuex store functions

2024-12-19 10:57 UTC, anttimaki requested changes
The changes match mostly what was planned, so in that sense this could be approved, but I think the suggested improvements are worthy of implementing right away.

One exception is that you didn't implement a getter for "next assign id" as was planned, nor was the plan augmented. Why's that?

Also generally speaking, while it's good to stick to the plan, I consider going a bit further than the plan if further improvement changes are discovered during implementation. Scope creep needs to be kept in mind though. I guess what I'm trying to say is to beware of the mentality where the plan is executed blindly, as it doesn't necessarily lead to best outcome.

2024-12-19 10:57 UTC, anttimaki commented on src/store/modules/DownloadModule.ts
> +                throw new R2Error(
Nitpick: Did you test this? Is the error message shown to user in the error modal like it's written here, or does it get overwritten somewhere along the way? If this error is shown to the user, I think the middle line might be too technical while offering the user no actionable information, nor provides anything for us to debug the issue. Something like "DownloadProgress with id ${oldDownloadObject.assignId} was not found" would at least help in debugging if the value turns out to be undefined or something?

2025-01-02 14:25 UTC, VilppeRiskidev commented
Improved based on the comments and rebased

2025-01-03 11:23 UTC, anttimaki requested changes

2025-01-03 11:23 UTC, anttimaki commented on src/components/views/DownloadModModal.vue
> +                            if (e instanceof R2Error) {
This should handle all caught errors regardless of the type, and in this specific method we should probably use `return reject(e)` as that's used in other places where errors are handled?

2025-01-03 11:23 UTC, anttimaki commented on src/components/views/DownloadModModal.vue
> +                            this.$store.commit('error/handleError', err);
Nitpick: as a personal preference, we could throw `err` here as we have the try-catch in place anyway. That way we don't have to duplicate the error handling. Applies to `downloadHandler` as well.

2025-01-03 11:23 UTC, anttimaki commented on src/components/views/DownloadModModal.vue
> +                    if (e instanceof R2Error) {
Here too all errors should be handled. Applies to `downloadHandler` as well.

2025-01-03 11:23 UTC, anttimaki commented on src/store/modules/DownloadModule.ts
> +            if (newDownloads[update.assignId].assignId !== update.assignId) {
How did you test this? I ran two test cases:

1. The call site uses hard coded `assignId: 0` for the updates. The first download works as expected. Consequent downloads remains at 0%, while in the DownloadMonitor I can see that the first download's progress bar is being updated. No error is thrown as the first downloads assignId is in fact still 0.

2. The call site uses hard coded `assignId: 9999` for the updates. `newDownloads[update.assignId]` returns `undefined`, so `newDownloads[update.assignId].assignId` throws an error. Since the call site currently only expects `R2Errors` the error silently ignored. Even if the call site shows the error modal for all error types, the download actually continues in the background.

So I guess the best approach would be to:

- Use the `if (index === -1)` check from my earlier example
- If the `assignId` is unknown AND the update object indicates download failure, throw the error to show the error modal
- If the `assignId` is unknown AND the update object indicates non-error states, just ignore the error (perhaps `console.error it)`. The progress on the modal won't update, but the modal itself should close once the installation finishes
  - Or you could get fancy and show a text that says the progress is unknown but the installation is still likely in progress instead of the progress bar on the progress modal

Other approaches might work too so let me know if you have any ideas. And remember to test my ideas when implementing them as this short of stuff happens.

I consider this issue critical.

2025-01-03 11:23 UTC, anttimaki commented on src/store/modules/DownloadModule.ts
> +            } else {
Nitpick: personal preference, but I see the `else` block a waste of lines and indentation when the `if` block always throws.

2025-01-03 11:24 UTC, anttimaki commented on src/pages/DownloadMonitor.vue
> +import Timeout = NodeJS.Timeout;
@VilppeRiskidev you could as a separate task/subtask for this so it's not forgotten (if you haven't already).

2025-01-07 13:44 UTC, VilppeRiskidev commented on src/store/modules/DownloadModule.ts
> +            if (newDownloads[update.assignId].assignId !== update.assignId) {
Ok this should now be ok, but this is the most unsure part of the PR.
at least now it doesn't stop downloads from continuing.
The `console.warn()` thing feels a bit spammy, but it shouldn't be happening in the normal use cases after all (or more like never).

2025-01-08 08:43 UTC, anttimaki requested changes
The commits in this PR should probably be squashed. We can't do that during merging while using the "stack all the approved changes in the same PR" approach, so you should do it manually and force push the changes.

2025-01-08 08:43 UTC, anttimaki commented on src/components/views/DownloadModModal.vue
> +                    this.$store.commit('error/handleError', e);
Now that the "if is R2Error" block is removed per my earlier request, `e` is `unknown` type and shouldn't be passed to `handleError` as is (there's no complaints about it due to the poor type support with this Vuex version). Instead, use `R2Error.fromThrownValue(e)`

2025-01-08 08:43 UTC, anttimaki commented on src/store/modules/DownloadModule.ts
> +                const err = new R2Error(
~Minor: when we consider the situation where `err` is thrown and consequently shown to user in error modal, the message might not be as informative as it could be. If the action the user triggered is "download FartMod", they're probably not that interested in the download status or assignIds. Perhaps the `name` of the error could be something like "Failed to download a mod" and the `message` something like "[mod name] could not be downloaded". The `solution` is fine as it is. To show the mod name we will have to change `UpdateObject.modName` to required attribute though.~

Scratch the above. What we haven't taken into consideration is that this error will always overshadow the error provided by DownloadProvider (the one we pass to `addSolutionsToError` helper). I think we don't want to do that, so we shouldn't throw anything here. This is based on an assumption that DownloadProvider will include an Error in the callback whenever the status is set as failure. I think it's a relatively safe assumption, so trying to sniff out whether it did or didn't would probably be a wasted effort.

Secondly, logging the error message as it's now in the cases when the download hasn't failed isn't ideal either, as in case someone checks the console, we don't want them to "Try initiating the download again" as then they will have multiple downloads of the same files progressing.

Therefore I think this whole if-block should just console.warn something simple like "Could not find DownloadProgress object with assignId x" and `return`.

Thoughts?

2025-01-08 08:43 UTC, anttimaki commented on src/store/modules/DownloadModule.ts
> +                // Just as a bonus, log if the DownloadProgress by the ID was located at the corresponding index of the array.
Doesn't the comment say exactly the opposite of what the code actually does? Anyway I think the code is simple enough so no comment is necessary here.

2025-01-08 08:43 UTC, anttimaki commented on src/store/modules/DownloadModule.ts
> +            newDownloads[update.assignId] = {...newDownloads[update.assignId], ...update};
Critical(?): isn't this a bug? Since we can't trust that `index === update.assignId`, shouldn't we use `index` to index the arrays here?

2025-01-08 12:26 UTC, VilppeRiskidev commented on src/store/modules/DownloadModule.ts
> +                // Just as a bonus, log if the DownloadProgress by the ID was located at the corresponding index of the array.
Oops, it was supposed to be "was not"... anyway, makes sense to remove the comment.

2025-01-08 12:28 UTC, VilppeRiskidev commented on src/store/modules/DownloadModule.ts
> +                const err = new R2Error(
Yeah makes sense 👍

2025-01-09 08:15 UTC, anttimaki commented on src/components/views/DownloadModModal.vue
> +                        this.$store.commit('error/handleError', e);
This instance should also use `R2Error.fromThrownValue(e)`.

2025-01-14 17:00 UTC, VilppeRiskidev commented
This is now a part of https://github.com/ebkr/r2modmanPlus/pull/1614

2025-01-14 17:00 UTC, closed without merging