Handle returned R2Errors
ebkr/r2modmanPlus pull request #923
Opened 2022-12-23 12:45 UTC by anttimaki

I'm putting this up here to discuss whether changes like these make sense. Generally speaking the code base contains places where R2Errors are returned, and the caller:

* Intentionally ignores the error and it makes sense to me given the context
* Intentionally ignores the error and I'm not sure if it's wise
* Just ignores the error and I can't tell whether it's intentional or not

Any thoughts what should be done in these cases?

---

Another issue: there's multiple places where settings are loaded, but then it's not checked if `.load()` returned R2Error or not. Given the recent addition of SettingsLoader, is this okay, or should we always check the return value?

---

Marking as a draft for discussion and because this haven't been tested thoroughly manually yet.

2023-01-17 21:22 UTC, ebkr requested changes

2023-01-17 21:22 UTC, ebkr commented on src/pages/Splash.vue
> +            if (isProton instanceof R2Error) {
I'm thinking that maybe we'd benefit by having errors that can be logged to Sentry but having things not present in modals.

This is one example of an error we'd probably not want to show to a user as that means that relevant Steam files have been modified, and that's not really something that the user can solve themselves.

2023-01-17 21:22 UTC, ebkr commented on src/r2mm/installing/profile_installers/GenericProfileInstaller.ts
> +        const err = await ConflictManagementProvider.instance.overrideInstalledState(mod, profile);
Could you verify that this doesn't cause any issues when installing BONEWORKS mods?
I've looked through the code and have a feeling it'll be fine, but would be good to sanity check.

2023-01-19 07:46 UTC, anttimaki commented
@ebkr this is a read receipt for your comments. I will look into both issues you mentioned, but don't quite know when.

2024-11-11 07:42 UTC, anttimaki commented
Closing an ancient PR. Never got around to doing what I said I would do, and this is now outdated. I think at least some of the issues have been fixed in other PRs in the meanwhile.

2024-11-11 07:42 UTC, closed without merging